---
services:
  db:
    image: postgres:15.1
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    ports:
      - 8081:8080

  rabbitmq:
    image: rabbitmq:3.12
    ports:
      - 5672:5672


  kafka:
    image: bitnami/kafka:3.6
    ports:
      - 9094:9094
    volumes:
      - kafkadata:/bitnami/kafka
    environment:
      KAFKA_CFG_NODE_ID: 0 
      KAFKA_CFG_PROCESS_ROLES: controller,broker 
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093 
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER 

volumes:
  pgdata:
  kafkadata:
